// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBciR5YZnyu41lyPCp-VPc0lWwsI1PfAv8',
    appId: '1:918043749701:android:c4743237492a0546d9622c',
    messagingSenderId: '918043749701',
    projectId: 'we-chat-12f99',
    storageBucket: 'we-chat-12f99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcNYmZ1W1n7x5TND-9Jj4_kalVqPimNEw',
    appId: '1:918043749701:ios:15a01271a54e60d5d9622c',
    messagingSenderId: '918043749701',
    projectId: 'we-chat-12f99',
    storageBucket: 'we-chat-12f99.appspot.com',
    androidClientId: '918043749701-hv0ir2to3o5h1a0ipmmeo1lpi5jqksva.apps.googleusercontent.com',
    iosClientId: '918043749701-67p2t495ed8oescgol4btm79978avjnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
